### ISSUE TITLE
required RAM size

### ISSUE THREAD

**Issue by YooEunseok** [HansiZeng/CL-DRD#2]
Hello,
What is the RAM size used in the experiment?
Is 128GB single server not enough to perform indexing like the code provided?

Thank you.

**Comment by HansiZeng** [comment]
It works fine for me in a similar RAM size. Can you give me more information on your problem, such as a screenshot of how your code failed?

**Comment by YooEunseok** [comment]
Thank you for your reply. Here it is. 
```
 python retriever/retrieve_top_passages.py --queries_path="/home/nlplab/hdd1/yoo/CL-DRD/data/queries.dev.tsv" --resume="/home/nlplab/hdd1/yoo/CL-DRD/checkpoints/checkpoint_120000.pth.tar" --index_path="/home/nlplab/hdd1/yoo/CL-DRD/index/checkpoint_120000.index" --output_path="/home/nlplab/hdd1/yoo/CL-DRD/outputs/dev"
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
INFO:faiss.loader:Loading faiss.
INFO:faiss.loader:Successfully loaded faiss.
retrieve dev queries
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_projector.bias', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_projector.bias', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
************************* share weights = False *************************
load model from ==> /home/nlplab/hdd1/yoo/CL-DRD/checkpoints/checkpoint_120000.pth.tar
load parallel wrapped model.
encode # 198 seqs: 198it [00:08, 22.74it/s]
# nan in embeddings: 0
Traceback (most recent call last):
  File "retriever/retrieve_top_passages.py", line 115, in <module>
    main(args)
  File "retriever/retrieve_top_passages.py", line 87, in main
    index = convert_index_to_gpu(index, 0, False)
  File "./retriever/retrieval_utils.py", line 163, in convert_index_to_gpu
    index = faiss.index_cpu_to_gpu(res, faiss_gpu_index, index, co)
  File "/home/nlplab/anaconda3/envs/DPR/lib/python3.8/site-packages/faiss/swigfaiss.py", line 10275, in index_cpu_to_gpu
    return _swigfaiss.index_cpu_to_gpu(provider, device, index, options)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /project/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type FlatData dev 0 space Device stream 0x56405daa2bd0 size 27162080256 bytes (cudaMalloc error out of memory [2])
```

**Comment by YooEunseok** [comment]
Also, can I know about the faiss version used?

**Comment by HansiZeng** [comment]
It looks like the error you're encountering may be related to the faiss library (``` ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'") ```). To resolve the issue, try the following steps:
1, Uninstall the current version of faiss you have installed
2, Reinstall faiss using the command ```conda install -c conda-forge faiss-gpu``` (Note: you should install faiss-gpu, not just faiss)
3, Try running your code again
If you continue to experience the same error, please provide additional information, and I will do my best to help you resolve the issue.

It's worth mentioning that the error could also be due to a GPU out-of-memory issue. For your reference I used an RTX-2080ti with 11GB of memory and had faiss version 1.7.3 installed.

**Comment by HansiZeng** [comment]
It is because the error ```ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")```

**Comment by YooEunseok** [comment]
I tried the method you advised me, but the error was not solved.
So I didn't upload the index to gpu and ran it on cpu, and the problem was solved.
(When running on cpu, it took about 35 minutes based on MSMARCO-dev set.)
Thank you for your kind reply.
